force-app/main/default/objects/song__c/song__c.object-meta.xml
<CustomObject>
    <description>Songs</description>
    <label>Song</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Song Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/song__c/fields/ChordPro_Content__c.field-meta.xml
<CustomField>
    <fullName>ChordPro_Content__c</fullName>
    <label>ChordPro Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/song__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SongChordEditor.cls
public with sharing class SongChordEditor {
    @AuraEnabled(cacheable=true)
    public static String getChordProContent(Id recordId) {
        Song__c song = [SELECT ChordPro_Content__c 
                       FROM Song__c 
                       WHERE Id = :recordId 
                       LIMIT 1];
        return song.ChordPro_Content__c;
    }

    @AuraEnabled
    public static void saveChordProContent(Id recordId, String content) {
        Song__c song = [SELECT Id 
                       FROM Song__c 
                       WHERE Id = :recordId 
                       LIMIT 1];
        
        song.ChordPro_Content__c = content;
        update song;
    }    
}