force-app/main/default/objects/song__c/song__c.object-meta.xml
<CustomObject>
    <description>Songs</description>
    <label>Song</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Song Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/song__c/fields/ChordPro_Status__c.field-meta.xml
<CustomField>
    <fullName>ChordPro_Status__c</fullName>
    <label>ChordPro Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/song__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SongRandomSelectorController.cls
public with sharing class SongRandomSelectorController {
    @AuraEnabled
    public static Id getRandomSongId() {
        List<Song__c> songs = [SELECT Id FROM Song__c where ChordPro_Status__c = 'In Progress' or ChordPro_Status__c = 'Done' order by Id];
        if (songs.isEmpty()) return null;
        Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), songs.size());
        return songs[idx].Id;
    }
}